### ISSUE TITLE
Un override crée des changements versionnés

### ISSUE THREAD

**Issue by vmourot** [opendigitaleducation/ode-mobile-framework#11]
Appliquer un override avec la commande `node ode-plugin.js override switch` créée des changements dans trois fichiers versionnés : 

- `package.json`
- `android/gradle.properties`
- `ios/appe/Info.plist`

C'est principalement embêtant pour `package.json` puisque pour le modifier, il est nécessaire de retirer l'override actif, de faire les changements et de commiter, puis de réappliquer l'override, sans quoi les changements effectués seront perdus lors du `node ode-plugin.js override restore`.

Il faut trouver un moyen pour que l'application d'un override n'ait pas d'impact sur les changements versionnés.

**Comment by JacquesBonet** [comment]
Une solution serait d'avoir autant de repos que d'override.
Afin de ne pas alourdir la gestion, transformer le repos ode-mobile-framework en un mono repos.
Ainsi cela permettrait de mettre les repos d'override dans le repos ode-mobile-framework.
l'aantage du mono repos:
- Chaque repos est versionné de facon indépendante
- Ces repos partage le meme espace physique, et sont donc ramené par un seul git clone.

Pour résumé un mono repos, c'est un repos contenant une liste de repos. Cette liste de repos étant archivé dans le repos parent. Chaque repos de la liste pouvant etre référencé en tant que tels.
