### ISSUE TITLE
Tests unitaires avec Jest ?

### ISSUE THREAD

**Issue by vmourot** [opendigitaleducation/ode-mobile-framework#12]
Comment mettre en place des tests unitaires avec Jest (déjà inclus dans le projet React Native) ?

**Comment by SLedunois** [comment]
Des tests unitaires ont été mis sur Schooltoring avec Jest/Enzyme : https://github.com/OPEN-ENT-NG/schooltoring.
Cela apporte une vrai plus-value en terme de non régression et n'est pas si coûteux à mettre en place.

**Comment by JacquesBonet** [comment]
Jest est pas mal effectivement pour tester le comportement d'un composant. Par contre il ne permet pas de s'assurer que le composant s'affiche correctement.
Storybook permet de faire cela. Il y a des extensions storybook (StoryShoot par exemple qui utilise Jest) qui permettent aussi de tester le comportement du composant.
https://storybook.js.org/docs/testing/structural-testing/
https://storybook.js.org/docs/testing/react-ui-testing/
