### ISSUE TITLE
Ajouter une couche service pour le module Conversation (Zimbra)

### ISSUE THREAD

**Issue by vmourot** [opendigitaleducation/ode-mobile-framework#25]
Actuellement le module fonctionnel Conversation dispose d'actions ("thunks") qui appellent directement l'API back de l'ENT.

L'idée serait d'encapsuler tous ces appels dans une couche service qui pourra être déclinée en plusieurs versions afin de supporter plusieurs APIs (entcore, zimbra, ...).

On retrouvera donc avec une interface ConversationService que devront implémenter ConversationEntcoreService et ConversationZimbraService.

Une configuration dans le module fonctionnel permettra de lui définir quelle coucher service il devra utiliser.

Tous les modules fonctionnels devront être fournis avec un service implémenté minimum.

Ce ticket sera l'occasion de tester une telle implémentation qui pourra ensuite être factorisée pour chacun des autres modules fonctionnels.

**Comment by SLedunois** [comment]
En version optimale, c'est le fonctionnement qu'il faut mettre en place. J'espère juste que des fonctionnalités custom Zimbra ne vont pas être demandées par la région
