### ISSUE TITLE
Comment créer un functional module sans application miroir côté serveur

### ISSUE THREAD

**Issue by rdjedjig** [opendigitaleducation/ode-mobile-framework#3]
On a 1 cas qu'on ne décrit pas explicitement dans la [https://github.com/opendigitaleducation/ode-mobile-framework/wiki/functional-module](https://github.com/opendigitaleducation/ode-mobile-framework/wiki/functional-module). Comment écrire un functional module indépendant du serveur. Par exemple :
- un module lanceur d'application
- un module lanceur de connecteur vie-scolaire

**Comment by vmourot** [comment]
Dans ode-mobile-framwork, un module fonctionnel est une entité technique cumulant un état Redux, une vue et une route qui y mène. Leurs fichiers de déclaration est traditionnellement de contenu dans `config.ts`, présent à la racine de chaque module fonctionnel.

Cette configuration comprend entre autres ces champs :
```javascript
{
    name: "mailbox", // Nom du module fonctionnel, équivaut au nom du dossier
    apiName: "Messagerie", // Nom correspondant côté serveur
    displayName: "Conversation", // Nom affiché dans Pocket
    iconName: "conversation" // Nom de l'icône utilisé
}
```

Gestion des droits
------------------
Le plus intéressant dans cette configuration réside dans la clé `apiName`.
Lors de la connexion de l'utilisateur, ode-mobile-framework va chercher la liste des "apps" dont il a les droits d'accès, et vérifie quels sont les modules fonctionnels dont la clé `apiName` est présente dans cette liste. Les modules absents de cette liste ne seront pas affichés.

Toutefois, il existe des modules fonctionnels qui n'ont pas d'app équivalente sur l'ENT (notamment le module "user").
Pour les afficher, il suffit de les ajouter manuellement dans la liste des apps disponibles :
```typescript
/* src/navigation/RootNavigator.tsx(142) */

const mapStateToProps = ({ user }) => ({
  apps: ["user", ...user.auth.apps], // Ici on a ajouté le module "user" manuellement (Sa clé `apiName` est égale à sa clé `name` car elle ne figure pas dans son config.json)
  notification: user.auth.notification
});
```

*Note : Le fonctionnement module "timeline" est différent, mais sera unifié dans quelques temps.*

Créer un lanceur d'applications
-------------------------------

La liste des "apps" est stockée dans le reducer à `state.user.auth.apps`.

Créer un lanceur d'application peut être fait en reprenant le même principe que le "MainNavigator" :
- Calcul de l'intersection entre les clés `apiName` des modules fonctionnels à afficher et la liste `state.user.auth.apps`.
- Les modules gérés par le connecteur peuvent être déclérés de la même manière ce qui est fait pour le routeur principal (dans "src/AppModules.ts")

Créer un module fonctionnel connecteur
--------------------------------------

À part les contraintes inhérentes à chaque module fonctionnel (Reducer, route et vue principale, incluant "&lt;module name&gt;/config.ts" et "&lt;module name&gt;/index.ts"), le contenu est entièrement libre.

Un connecteur peut simplement prendre la forme d'un simple module fonctionnel qui saura soit rediriger l'utilisateur sur son navigateur, soit d'incorporer le site web connecté à l'aide d'une `<Webview>`.
