### ISSUE TITLE
Isolement des types

### ISSUE THREAD

**Issue by vmourot** [opendigitaleducation/ode-mobile-framework#36]
Plutôt que de centraliser les types d'un module dans un sous-dossier types (qui peut s'avérer fourre-tout à mélanger les types pour le state, pour les actions, et pour les containers/composants), je propose une autre façon d'isoler les types :

- On dissocie le state du reducer : le type du state sera indépendant du reste et on pourra l'importer partout dans le module
- On sort les action types pour que le reducer n'ait plus recours aux fichiers contant les actions creators et les thunks
- Les types des props et du state d'un composant/container sont dans le même fichier que le composant/container.

De cette manière, on ne craint plus d'imports circulaire au sein d'un même module fonctionnel, mais on garde une séparation des responsabilités correcte.

![BA0F429C-9C85-4478-8663-1D8C54BDF902_1_105_c](https://user-images.githubusercontent.com/47815741/66849567-623fb600-ef77-11e9-952e-0b9297b84fea.jpeg)

**Comment by JacquesBonet** [comment]
Je ne sais pas si cela correspond exactement à tes remarques, mes j'ai organisé les types ds le dossier types en sous dossiers

![image](https://user-images.githubusercontent.com/173393/66903931-919c0480-f003-11e9-858d-e19593bf9baf.png)
